// CRIE 3 VARIAVEIS CONTENDO STRINGER

// CRIE 3 OBJETOS COM 2 STRINGER E UM NUMERO

// CRIE UMA FUNCAO QUE RETORNA UMA OPERACAO

// CRIE UMA FUNCAO PURA

// CRIE UMA ARROW FUNCTION

// CITE OS TIPOS DE OPERADORES EM JS

// CITE OS TIPOS DE DADOS EM JS

